[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
    nmap <silent> gd :LspDefinition<CR>
    nmap <silent> gtd :tab LspDefinition<CR>
    nmap <silent> <f2> :LspRename<CR>
    nmap <silent> <Leader>d :LspTypeDefinition<CR>
    nmap <silent> <Leader>r :LspReferences<CR>
    nmap <silent> <Leader>i :LspImplementation<CR>
    let g:lsp_diagnostics_enabled = 1
    let g:lsp_diagnostics_echo_cursor = 1
    let g:asyncomplete_popup_delay = 200
    let g:lsp_text_edit_enabled = 0
'''
[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  let g:molokai_original = 1
  let g:rehash256 = 1

  colorscheme molokai
'''

