[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'zerowidth/vim-copy-as-rtf'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  let g:molokai_original = 1
  let g:rehash256 = 1

  colorscheme molokai
'''

